#!/bin/sh

### This example script shows how to drive mailaprop.py to produce a
### file of email addresses in the format that mailaprop.el expects.

# MAYBE CHANGE THIS: Tell the script where mailaprop.py lives.
MAILAPROP=mailaprop.py

# CHANGE THIS: Say where your file of email addresses will live.
OUTFILE=${HOME}/private/mailaprop/mailaprop-addresses.eld

OUTFILE_TMP=${OUTFILE}.tmp
> ${OUTFILE_TMP}

echo ";;; THIS FILE GENERATED WAS AUTOMATICALLY GENERATED BY:"       \
   >> ${OUTFILE_TMP}
echo ";;; " >> ${OUTFILE_TMP}
echo ";;;   https://github.com/kfogel/mailaprop/"                    \
   >> ${OUTFILE_TMP}
echo ";;; " >> ${OUTFILE_TMP}
echo ";;; YOU PROBABLY DON'T WANT TO EDIT IT BY HAND.  INSTEAD, SEE" \
   >> ${OUTFILE_TMP}
echo ";;; THE DOCUMENTATION THERE FOR MORE INFORMATION."             \
   >> ${OUTFILE_TMP}
echo "" >> ${OUTFILE_TMP}

echo "(" >> ${OUTFILE_TMP}

# CHANGE THIS: Pipe *all* of your email, which may be spread across
#              many files, through one invocation of mailaprop.py.
cat test-data/*.mbox | ${MAILAPROP} >> ${OUTFILE_TMP}

echo ")" >> ${OUTFILE_TMP}

mv ${OUTFILE_TMP} ${OUTFILE}

echo "Email address database created: '${OUTFILE}'"
